### ISSUE TITLE
`make` doesn't work (Makefile doesn't explicitly specify bash)

### ISSUE THREAD

**Issue by sboosali** [reflex-frp/reflex-native#2]
we should either require bash, like this pr:

https://github.com/reflex-frp/reflex-native/pull/1

or not use non-`sh` features, like

    set -eo pipefail

**Comment by Dridus** [comment]
thanks! I merged #1 as-is though it might need tweaking on NixOS (or any other place that puts bash somewhere other than `/bin`)
